### ISSUE TITLE
maven-plugin-api 依赖问题

### ISSUE THREAD

**Issue by selfly** [youyoudanshui/userAgentUtil#2]
不错的库，刚好满足我的需求又够小巧。
多问一句，解析浏览器的user-agent为什么要做成Maven插件呢？相信作者有自己的理由，
但是弄成可选依赖会不会好一点，毕竟这个库的作用在多数场景下应该不是当作Maven插件来跑的，
强迫症还得手动exclusion maven-plugin-api依赖

**Comment by youyoudanshui** [comment]
> 

你好，这是因为有用户希望我将插件上传maven中央仓库，方便使用和更新，如果你是直接下载源码使用的，可以将依赖去掉

**Comment by youyoudanshui** [comment]
你好，多谢指出问题。确实不需要做成Maven插件，已将maven-plugin-api依赖移去，请升级最新版本使用。
